baseURL = "https://77doc.wss.cool/"
languageCode = "zh-cn"
title = "新手村生存攻略"
theme = "book"
publishDir = "docs"

BookRepo = 'https://github.com/wangshushuo/77'
BookEditPath = 'edit/master/exampleSite'

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
